/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-primary-fixed": "#001a41",
              "on-secondary-fixed-variant": "#00531c",
              "tertiary-fixed-dim": "#c2c1ff",
              "tertiary-container": "#6664e4",
              "inverse-on-surface": "#f1f0f5",
              "outline": "#717786",
              "on-error-container": "#93000a",
              "on-primary": "#ffffff",
              "on-tertiary-fixed-variant": "#3631b4",
              "inverse-primary": "#adc6ff",
              "surface-variant": "#e3e2e7",
              "secondary-fixed": "#72fe88",
              "outline-variant": "#c1c6d7",
              "on-surface-variant": "#414755",
              "primary": "#0058bc",
              "on-secondary": "#ffffff",
              "secondary": "#006e28",
              "surface-container-lowest": "#ffffff",
              "surface-tint": "#005bc1",
              "on-primary-fixed-variant": "#004493",
              "on-secondary-fixed": "#002107",
              "surface-container-low": "#f4f3f8",
              "on-primary-container": "#fefcff",
              "secondary-fixed-dim": "#53e16f",
              "surface-container": "#eeedf3",
              "surface-bright": "#faf9fe",
              "inverse-surface": "#2f3034",
              "tertiary": "#4c4aca",
              "surface": "#faf9fe",
              "error": "#ba1a1a",
              "on-tertiary-container": "#fffbff",
              "secondary-container": "#6ffb85",
              "surface-container-high": "#e9e7ed",
              "on-background": "#1a1b1f",
              "primary-fixed": "#d8e2ff",
              "on-surface": "#1a1b1f",
              "primary-fixed-dim": "#adc6ff",
              "surface-container-highest": "#e3e2e7",
              "surface-dim": "#dad9df",
              "error-container": "#ffdad6",
              "tertiary-fixed": "#e2dfff",
              "on-tertiary": "#ffffff",
              "on-error": "#ffffff",
              "on-secondary-container": "#00732a",
              "on-tertiary-fixed": "#0c006a",
              "primary-container": "#0070eb",
              "background": "#faf9fe"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "gutter": "20px",
              "lg": "24px",
              "md": "16px",
              "unit": "4px",
              "sm": "8px",
              "xs": "4px",
              "xl": "32px",
              "margin-desktop": "40px",
              "xxl": "48px"
          },
          "fontFamily": {
              "label-md": ["Inter", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "display": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "600"}],
              "body-md": ["15px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-md": ["22px", {"lineHeight": "28px", "fontWeight": "600"}],
              "body-lg": ["17px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
          }
      }
  },
  plugins: [],
}