/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "primary": "var(--color-primary)",
              "on-primary": "var(--color-on-primary)",
              "primary-container": "var(--color-primary-container)",
              "on-primary-container": "var(--color-on-primary-container)",
              "secondary": "var(--color-secondary)",
              "on-secondary": "var(--color-on-secondary)",
              "secondary-container": "var(--color-secondary-container)",
              "on-secondary-container": "var(--color-on-secondary-container)",
              "tertiary": "var(--color-tertiary)",
              "on-tertiary": "var(--color-on-tertiary)",
              "tertiary-container": "var(--color-tertiary-container)",
              "on-tertiary-container": "var(--color-on-tertiary-container)",
              "error": "var(--color-error)",
              "on-error": "var(--color-on-error)",
              "error-container": "var(--color-error-container)",
              "on-error-container": "var(--color-on-error-container)",
              "surface": "var(--color-surface)",
              "surface-dim": "var(--color-surface-dim)",
              "surface-bright": "var(--color-surface-bright)",
              "surface-container-lowest": "var(--color-surface-container-lowest)",
              "surface-container-low": "var(--color-surface-container-low)",
              "surface-container": "var(--color-surface-container)",
              "surface-container-high": "var(--color-surface-container-high)",
              "surface-container-highest": "var(--color-surface-container-highest)",
              "on-surface": "var(--color-on-surface)",
              "on-surface-variant": "var(--color-on-surface-variant)",
              "surface-variant": "var(--color-surface-variant)",
              "surface-tint": "var(--color-surface-tint)",
              "inverse-surface": "var(--color-inverse-surface)",
              "inverse-on-surface": "var(--color-inverse-on-surface)",
              "inverse-primary": "var(--color-inverse-primary)",
              "outline": "var(--color-outline)",
              "outline-variant": "var(--color-outline-variant)",
              "background": "var(--color-background)",
              "on-background": "var(--color-on-background)",
              "primary-fixed": "var(--color-primary-fixed)",
              "primary-fixed-dim": "var(--color-primary-fixed-dim)",
              "on-primary-fixed": "var(--color-on-primary-fixed)",
              "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
              "secondary-fixed": "var(--color-secondary-fixed)",
              "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
              "on-secondary-fixed": "var(--color-on-secondary-fixed)",
              "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
              "tertiary-fixed": "var(--color-tertiary-fixed)",
              "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
              "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
              "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "gutter": "20px",
              "lg": "24px",
              "md": "16px",
              "unit": "4px",
              "sm": "8px",
              "xs": "4px",
              "xl": "32px",
              "margin-desktop": "40px",
              "xxl": "48px"
          },
          "fontFamily": {
              "label-md": ["Inter", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "display": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "600"}],
              "body-md": ["15px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-md": ["22px", {"lineHeight": "28px", "fontWeight": "600"}],
              "body-lg": ["17px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
          }
      }
  },
  plugins: [],
}